export const HOME_SCREEN = 'lxm.HomeScreen'
export const PLAY_DETAIL_SCREEN = 'lxm.PlayDetailScreen'
export const SONGLIST_DETAIL_SCREEN = 'lxm.SonglistDetailScreen'
export const COMMENT_SCREEN = 'lxm.CommentScreen'
// 2026-10-05：删除未注册的 VERSION_MODAL（P1-13）
export const PACT_MODAL = 'lxm.PactModal'
export const SYNC_MODE_MODAL = 'lxm.SyncModeModal'
export const ARTIST_DETAIL_SCREEN = 'lxm.ArtistDetailScreen'
export const ALBUM_DETAIL_SCREEN = 'lxm.AlbumDetailScreen'
export const SIMILAR_SONGS_SCREEN = 'lxm.SimilarSongsScreen'
export const DOWNLOAD_MANAGER_SCREEN = 'lxm.DownloadManagerScreen'
export const SETTING_DETAIL_SCREEN = 'lxm.SettingDetailScreen'
export const ANNOUNCEMENT_MODAL = 'lxm.AnnouncementModal'
// export const SETTING_SCREEN = 'lxm.SettingScreen'
export const TOAST_SCREEN = 'lxm.ToastScreen'
